version: 2
jobs:
  mac-swift5:
    macos:
      xcode: "11.7.0"
    steps:
      - checkout
      - run: brew tap novi/tap && brew install novi/tap/cmecab
      - run: swift test
  linux-swift5.2:
    docker:
      - image: swift:5.2
    steps:
      - checkout
      - run: apt-get update && apt-get install -y libmecab-dev mecab-ipadic-utf8
      - run: swift test --enable-test-discovery
workflows:
  version: 2
  build_and_test:
    jobs:
      - mac-swift5
      - linux-swift5.2

